### ISSUE TITLE
Error on startup - google.protobuf.message.DecodeError: Truncated message.

### ISSUE THREAD

**Issue by srirams** [asmirnou/watsor#4] opened 2020-07-07 07:30 UTC
Log file: https://pastebin.com/rrtQyCb2

I'm using the latest version of tensorflow (2.x) because I'm running python 3.8 and tensorflow 1 doesn't seem to be available for python >= 3.8.

**Comment by asmirnou** [comment] 2020-07-07 08:30
It due to the wrong model file. The file `frozen_inference_graph.pb` inside the downloaded archive has to be renamed to `cpu.pb` and put into `model/` folder, `saved_model.pb` is for other purposes.

I'll make the documentation more clear about that.

**Comment by srirams** [comment] 2020-07-08 06:16
Thanks, that fixed it! 

Seems to be working well, but it is missing a lot compared to frigate, but no false positives- whereas frigate has a better detection rate, but also a lot of false positives.

**Comment by asmirnou** [comment] 2020-07-08 17:49
Good, closing as the problem is resolved.

**Closed by asmirnou** 2020-07-08 17:49 UTC
